# build specified according to parent directory context
# so current directory=log-ingester-elasticsearch folder

FROM python:3-alpine
 
# Create app directory
WORKDIR /app
 
# Install app dependencies
COPY query_interface/requirements.txt ./
 
RUN pip install -r requirements.txt
 
# Bundle app source
COPY query_interface .
# copy docker related env into root directory
COPY .env ./..
 
EXPOSE 5000

CMD [ "flask", "run","--host","0.0.0.0","--port","5000"]