version: "3.8"
volumes:
  ingester-volume:
services:
  elastic:
    image: elasticsearch:8.11.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - ingester-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test:     
        [
          "CMD-SHELL",
          "curl -s -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"
        ]
      interval: 10s
      timeout: 10s
      retries: 24
  query-interface:
    build: ./query_interface
    ports:
      - "5000:5000"
    depends_on:
      elastic:
        condition: service_healthy
  ingester-server:
    build: ./ingester_server
    ports:
      - "3000:3000"
    depends_on:
      elastic:
        condition: service_healthy